version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=shedule
      - POSTGRES_PASSWORD=shedule
      - POSTGRES_DB=schedule_db
    ports:
      - "5433:5432"
    networks:
      - custom
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  custom:
    driver: bridge
