version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=schedule_db
    ports:
      - "5433:5432"
    networks:
      - custom
    volumes:
      - ./db_data:/var/lib/postgresql/data
  db_test:
    container_name: "db_test"
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=123456_test
      - POSTGRES_DB=schedule_db_test
    ports:
      - "5434:5432"
    networks:
      - custom
    volumes:
      - ./db_data:/var/lib/postgresql/data

networks:
  custom:
    driver: bridge
